// ข้อมูลเริ่มต้นสำหรับ 1.4 Risk Assessment of Asset - ประเมินความเสี่ยง
// สกัดจากไฟล์ 1.4 Risk Assessment of Asset .xlsx แผ่น 'ใช้จริง Asset Risk Assessment'

export const DEFAULT_ASSET_RISK_HEADER = {
  "evaluator": "สมาชิกคณะกรรมการพิจารณาความเสี่ยง",
  "recorder": "นายธนกฤต นิธิตันติปัญญา, สำนักงานสาธารณสุขจังหวัดสระแก้ว",
  "meeting_date": "25 กุมภาพันธ์ 2569",
  "location": "Data Center, กลุ่มงานสุขภาพดิจิทัล",
  "address": "609 สำนักงานสาธารณสุขจังหวัดสระแก้ว ต.ท่าเกษม อ.เมืองสระแก้ว จ.สระแก้ว 27000",
  "critical_service": "All critical application"
};

export const DEFAULT_ASSET_RISK_LOGS = [
  {
    "id": "log_1",
    "date": "2 ก.ย. 2567",
    "detail": "เริ่มดำเนินการสร้าง Template จนแล้วเสร็จและทำการระบุวัตถุประสงค์ (Objective) และกำหนดเกณฑ์ที่ใช้ในการประเมิน ( Criteria)"
  },
  {
    "id": "log_2",
    "date": "9 ก.ย. 2567",
    "detail": "ดำเนินการจัดการประเมินความเสี่ยงและทำการอัพเดทสถานะ"
  },
  {
    "id": "log_3",
    "date": "23 ก.ย. 2567",
    "detail": "ทำการประเมินสถานภาพอีกครั้งอีกครั้ง เพื่อประเมินความพร้อมในการตรวจสอบ"
  }
];

export const ASSET_RISK_CLUSTERS = [
  'Application-Major',
  'Application-Minor',
  'HW-Servers',
  'HW-Router/Firewall',
  'HW-Others',
  'HW-Switch',
  'HW-WIFI',
  'SW-Windows',
  'SW-Others'
];

export const ASSET_RISK_ITEMS = [
  {
    "id": "asset_risk_1",
    "order_num": 1,
    "cluster": "Application-Major",
    "asset_name": "Pay Slip",
    "description": "Web Application ออกใบสลิปเงินเดือน",
    "concerned_app": "ระบบเงินเดือน",
    "critical_service": "รองรับการบันทึกข้อมูลเงินเดือนของบุคลากรจากงานการเงิน และออกใบสลิปเงินเดือนแบบออนไลน์ให้กับบุคลากรภายในสำนักงานสาธารณสุขจังหวัดสระแก้ว",
    "threat": "การเจาะระบบเพื่อแก้ไขข้อมูลเงินเดือน หรือข้อมูลรั่วไหล",
    "vulnerability": "การตั้งรหัสผ่านที่เดาได้ง่าย, ไม่มี MFA, หรือมีช่องโหว่ SQL Injection",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 3,
    "impact": 5,
    "risk_level": 15,
    "asset_owner": "หัวหน้างานการเงินและบัญชี",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "บริหารจัดการความปลอดภัยข้อมูลบุคคลและระบบงานหลัก",
    "sub_actions": [
      {
        "id": "sub_1_1",
        "sub_no": 1,
        "name": "เปิดใช้งาน MFA (การยืนยันตัวตน 2 ชั้น) เพื่อป้องกันการเข้าถึงข้อมูลเงินเดือน",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 0,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  },
  {
    "id": "asset_risk_2",
    "order_num": 2,
    "cluster": "Application-Major",
    "asset_name": "Plan-D",
    "description": "ระบบ ERP back office ของสำนักงาน",
    "concerned_app": "Web App ระบบ ERP back office ของสำนักงาน",
    "critical_service": "ระบบงานด้านสารบรรณและ Back Office อื่นๆ รองรับการบริหารจัดการข้อมูล การบันทึกข้อมูล",
    "threat": "การเจาะระบบเพื่อแก้ไขข้อมูลธรการ และงาน Backoffice รวมถึงข้อมูลบุคลากร",
    "vulnerability": "การตั้งรหัสผ่านที่เดาได้ง่าย, ไม่มี MFA, หรือมีช่องโหว่ SQL Injection",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 2,
    "impact": 5,
    "risk_level": 10,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "บริหารจัดการความปลอดภัยข้อมูลบุคคลและระบบงานหลัก",
    "sub_actions": [
      {
        "id": "sub_2_1",
        "sub_no": 1,
        "name": "กำหนดสิทธิ์เข้าถึงตามบทบาท (RBAC) ให้เจ้าหน้าที่เข้าถึงเฉพาะข้อมูลที่จำเป็น",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 100,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": null,
        "further_action": ""
      }
    ]
  },
  {
    "id": "asset_risk_3",
    "order_num": 3,
    "cluster": "Application-Minor",
    "asset_name": "WebEx",
    "description": "ระบบประชุมออนไลน์ Online Conference",
    "concerned_app": "Software บริหารจัดการการประชุมออนไลน์",
    "critical_service": "บริหารจัดการ สร้างลิงค์ประชุม การประชุมผ่านรับบออนไลน์",
    "threat": "การดักฟังข้อมูลการประชุม หรือการเข้าถึงการประชุมโดยไม่ได้รับอนุญาต",
    "vulnerability": "การแชร์ลิงก์ประชุมสาธารณะเกินไป หรือไม่ได้อัปเดตเวอร์ชันซอฟต์แวร์ล่าสุด",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 1,
    "impact": 2,
    "risk_level": 2,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Continue Monitoring",
    "treatment_plan_main": "บริหารจัดการความปลอดภัยระบบงาน",
    "sub_actions": [
      {
        "id": "sub_3_1",
        "sub_no": 1,
        "name": "",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 100,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  },
  {
    "id": "asset_risk_4",
    "order_num": 4,
    "cluster": "Application-Minor",
    "asset_name": "ระบบสารบรรณกระทรวง สธ.",
    "description": "รับส่งหนังสือออนไลน์จากสำนักงานปลัดกระทรวงสาธารณสุข",
    "concerned_app": "ระบบสารบรรณของ\nสป.สธ.",
    "critical_service": "สารบรรณ",
    "threat": "การดักข้อมูลหนังสือราชการสำคัญ ลับ หรือการเข้าถึงเอกสารโดยไม่ได้รับอนุญาต",
    "vulnerability": "ไม่ได้อัปเดตเวอร์ชันซอฟต์แวร์ล่าสุด",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 2,
    "impact": 5,
    "risk_level": 10,
    "asset_owner": "หัวหน้างานธุรการ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "บริหารจัดการความปลอดภัยข้อมูลบุคคลและระบบงานหลัก",
    "sub_actions": [
      {
        "id": "sub_4_1",
        "sub_no": 1,
        "name": "จำกัดการเข้าถึงเฉพาะภายในเครือข่าย (Intranet) หรือผ่าน VPN เท่านั้น/แยก VLAN",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 100,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  },
  {
    "id": "asset_risk_5",
    "order_num": 5,
    "cluster": "HW-Servers",
    "asset_name": "Web : sko.moph.go.th/research",
    "description": "Web site ให้บริการเผยแพร่ผลงานวิชาการระดับจังหวัด",
    "concerned_app": "ระบบเผยแพร่ผลงานวิชาการ",
    "critical_service": "พื้นที่ให้บุคลากรภายในจังหวัดสระแก้วนำผลงานวิชาการมาประกาศเผยแพร่",
    "threat": "การโจมตีหน้าเว็บ (Defacement) หรือ Malware",
    "vulnerability": "CMS (เช่น WordPress) ไม่ได้อัปเดต Patch หรือไม่มีการสำรองข้อมูลแยกส่วน",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 2,
    "impact": 4,
    "risk_level": 8,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "เฝ้าระวังและป้องกันภัยคุกคามเว็บไซต์สำนักงาน",
    "sub_actions": [
      {
        "id": "sub_5_1",
        "sub_no": 1,
        "name": "สำรองข้อมูลเว็บไซต์แบบ Offline เพื่อป้องกันกรณีถูกลบข้อมูลหรือถูกแฮก",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 20,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": null,
        "further_action": ""
      }
    ]
  },
  {
    "id": "asset_risk_6",
    "order_num": 6,
    "cluster": "HW-Servers",
    "asset_name": "Web : sko.moph.go.th",
    "description": "Web Application ของสำนักงานสาธารณสุขจังหวัดสระแก้ว",
    "concerned_app": "Web site สำนักงานสาธารณสุขจังหวัดสระแก้ว",
    "critical_service": "ให้บริการเว็บสำหรับให้ข้อมูลและประชาสัมพันธ์ ข้อมูลและการดำเนินงานต่างๆ ของสำนักงานสาธารณสุขจังหวัดสระแก้ว",
    "threat": "การโจมตีหน้าเว็บ (Defacement) หรือ Malware",
    "vulnerability": "CMS (เช่น WordPress) ไม่ได้อัปเดต Patch หรือไม่มีการสำรองข้อมูลแยกส่วน",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 2,
    "impact": 4,
    "risk_level": 8,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "เฝ้าระวังและป้องกันภัยคุกคามเว็บไซต์สำนักงาน",
    "sub_actions": [
      {
        "id": "sub_6_1",
        "sub_no": 1,
        "name": "ติดตั้ง Web Application Firewall (WAF) เพื่อป้องกันการโจมตีหน้าเว็บ",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 100,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  },
  {
    "id": "asset_risk_7",
    "order_num": 7,
    "cluster": "HW-Router/Firewall",
    "asset_name": "zyxel router",
    "description": "บริการอินเตอร์เน็ต NT",
    "concerned_app": "เว็บสำนักงาน",
    "critical_service": "เชื่อมต่อ เครื่องข่าย Gnode ของกระทรวงสาธารณสุข",
    "threat": "บริการอินเทอร์เน็ตล่ม หรือการโจมตีจากภายนอกผ่านพอร์ตที่เปิดทิ้งไว้",
    "vulnerability": "มีผู้ให้บริการรายเดียว (Single ISP), การตั้งค่า Firewall ไม่รัดกุม",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 3,
    "impact": 4,
    "risk_level": 12,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "เพิ่มประสิทธิภาพความมั่นคงปลอดภัยเครือข่าย",
    "sub_actions": [
      {
        "id": "sub_7_1",
        "sub_no": 1,
        "name": "จัดหา Link อินเทอร์เน็ตสำรอง (Backup Link) จากผู้ให้บริการรายอื่น",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 0,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  },
  {
    "id": "asset_risk_8",
    "order_num": 8,
    "cluster": "HW-Router/Firewall",
    "asset_name": "Fortigate 100F",
    "description": "ระบบป้องกันเครือข่ายภายใน",
    "concerned_app": "Firewall",
    "critical_service": "ระบบป้องกันภัยคุกคามเครือข่ายภายในของสำนักงานสาธารณสุขจังหวัดสระแก้ว",
    "threat": "การบุกรุกเครือข่ายภายใน หรือ Log เต็มจนหยุดทำงาน",
    "vulnerability": "Firmware เก่าเกินไป หรือการตั้งค่า Rules ที่หลวมเกินความจำเป็น",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 2,
    "impact": 3,
    "risk_level": 6,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "เพิ่มประสิทธิภาพความมั่นคงปลอดภัยเครือข่าย",
    "sub_actions": [
      {
        "id": "sub_8_1",
        "sub_no": 1,
        "name": "อัปเดต Firmware และตรวจสอบกฎ (Rule) การเข้า-ออกให้รัดกุมเสมอ",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 90,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": null,
        "further_action": ""
      }
    ]
  },
  {
    "id": "asset_risk_9",
    "order_num": 9,
    "cluster": "HW-Others",
    "asset_name": "Scan Face Hikvision",
    "description": "อุปกรณ์สแกนใบหน้าบันทึกและตรวจสอบเวลา เข้า-ออก การทำงาน",
    "concerned_app": "ระบบจัดการและประชาสัมพันธ์",
    "critical_service": "จัดเก็บข้อมูลใบหน้าบุคลากร",
    "threat": "ข้อมูลอัตลักษณ์บุคคล (Biometric) สูญหาย หรือเครื่องถูกแฮกเพื่อแก้เวลา",
    "vulnerability": "ตัวเครื่องเชื่อมต่อเครือข่ายโดยไม่มีการจำกัดสิทธิ์เข้าถึง, ข้อมูลไม่ได้เข้ารหัส",
    "existing_controls": "มีระบบควบคุมการเข้าถึงและสำรองข้อมูลตามรอบปกติ",
    "impact_c": true,
    "impact_i": true,
    "impact_a": true,
    "severity_f": false,
    "severity_s": false,
    "severity_r": true,
    "severity_i": true,
    "severity_l": true,
    "severity_o": true,
    "likelihood": 1,
    "impact": 5,
    "risk_level": 5,
    "asset_owner": "หัวหน้างานเทคโนโลยีสารสนเทศ",
    "treatment": "Mitigate Risk",
    "treatment_plan_main": "บริหารจัดการความปลอดภัยข้อมูลบุคคลและระบบงานหลัก",
    "sub_actions": [
      {
        "id": "sub_9_1",
        "sub_no": 1,
        "name": "แยกวงเครือข่าย (VLAN) และเปลี่ยนรหัสผ่านเริ่มต้น (Default Password)",
        "expected_date": "ภายใน 30 ก.ย. 69",
        "progress_percent": 90,
        "done_date": "15 ก.ย. 69",
        "residual_c": false,
        "residual_i": false,
        "residual_a": false,
        "residual_f": false,
        "residual_s": false,
        "residual_r": false,
        "residual_i_sev": false,
        "residual_l": false,
        "residual_o": false,
        "residual_likelihood": 1,
        "residual_impact": 1,
        "residual_risk_level": 1,
        "further_action": "เฝ้าติดตามเป็นระยะ"
      }
    ]
  }
];

export const ASSET_RISK_CRITERIA_LIKELIHOOD = [
  { level: 1, nameEn: 'Rare', nameTh: 'เกิดขึ้นได้ยาก (ปีละไม่เกิน 1 ครั้ง)' },
  { level: 2, nameEn: 'Unlikely', nameTh: 'มีโอกาสเกิดขึ้นน้อย (ปีละ 1-2 ครั้ง)' },
  { level: 3, nameEn: 'Moderate', nameTh: 'อาจเกิดขึ้น (ทุก 3-6 เดือน)' },
  { level: 4, nameEn: 'Likely', nameTh: 'มีโอกาสเกิดขึ้น (ทุกเดือน)' },
  { level: 5, nameEn: 'Almost Certain', nameTh: 'เกือบเกิดขึ้นแน่นอน (ทุกสัปดาห์หรือประจำ)' }
];

export const ASSET_RISK_CRITERIA_SEVERITY = [
  { level: 5, name: 'Severe (ระดับวิกฤต ข)', desc: 'ส่งผลกระทบร้ายแรงต่อระบบบริการสำคัญ ข้อมูลความลับรั่วไหลสูง ไม่สามารถให้บริการได้เกิน 24 ชม.' },
  { level: 4, name: 'Significant (ระดับวิกฤต ก)', desc: 'ระบบหยุดชะงักชั่วคราว กระทบผู้รับบริการในวงกว้าง แต่กู้คืนได้ตามเกณฑ์ RTO' },
  { level: 3, name: 'Moderate (ระดับร้ายแรง)', desc: 'กระทบระบบงานบางส่วน ประสิทธิภาพลดลง มีแผนรับมือชัดเจน' },
  { level: 2, name: 'Minor (ระดับไม่ร้ายแรง)', desc: 'กระทบเล็กน้อย แก้ไขได้ทันทีในระดับปฏิบัติการ' },
  { level: 1, name: 'Insignificant (ไม่มีผลกระทบ/เล็กน้อยมาก)', desc: 'ไม่มีผลกระทบต่อระบบงานหลักและการบริการ' }
];

export const ASSET_RISK_LEVEL_THRESHOLDS = [
  { level: 'Extreme / Very High', min: 20, max: 25, color: '#ef4444', text: 'ความเสี่ยงวิกฤต (20-25)', action: 'ต้องดำเนินการแก้ไขทันทีและติดตามใกล้ชิด' },
  { level: 'High', min: 10, max: 19, color: '#f97316', text: 'ความเสี่ยงสูง (10-19)', action: 'ต้องมีมาตรการจัดการความเสี่ยงชัดเจน' },
  { level: 'Moderate', min: 4, max: 9, color: '#eab308', text: 'ความเสี่ยงปานกลาง (4-9)', action: 'เฝ้าระวังและติดตามตามรอบปกติ' },
  { level: 'Low', min: 1, max: 3, color: '#22c55e', text: 'ความเสี่ยงต่ำ (1-3)', action: 'ยอมรับความเสี่ยงได้และเฝ้าระวัง' }
];
